In [9]:
import sqlite3
import pandas as pd

conexion = sqlite3.connect("../bases_datos/ventas.db")

Consultas con join

In [10]:
consulta = """
    SELECT v.IdVenta,
           c.NombreCliente,  
           v.FechaVenta
    FROM Ventas v
    INNER JOIN Clientes c
      ON v.IdCliente = c.IdCliente
"""
ventas = pd.read_sql_query(consulta, conexion)
ventas.head()

   IdVenta          NombreCliente  FechaVenta
0        1   Hierros Levante S.A.  2025-01-08
1        2        Clínica Benalúa  2025-01-15
2        3   Academia San Vicente  2025-01-28
3        4  Restaurante El Puerto  2025-02-04
4        5   Distribuciones Costa  2025-02-17

In [11]:
ventas = pd.read_sql_query(consulta, conexion)
ventas.head()

   IdVenta          NombreCliente  FechaVenta
0        1   Hierros Levante S.A.  2025-01-08
1        2        Clínica Benalúa  2025-01-15
2        3   Academia San Vicente  2025-01-28
3        4  Restaurante El Puerto  2025-02-04
4        5   Distribuciones Costa  2025-02-17